import Head from "next/head";
import { MDBBtn } from "mdb-react-ui-kit";
import { Inter } from "next/font/google";
import Carousel from "@/components/Carousel";
import LatestPosts from "@/components/LatestPosts";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>SSDC Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Carousel />
      <LatestPosts />
    </>
  );
}
